# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
podfile: Example/Podfile
before_install:
  - env
  - locale
  - rvm use system
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod --version
  - pod setup --silent
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks
script:
  - set -o pipefail
  - pod lib lint
  - xcodebuild test -workspace Example/RxPager.xcworkspace -scheme RxPager-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
